Deploy automatic bump, changes to timesheet report (#142)
* Enhanced documentation on cz commit and bump (#138)

* Big refactoring of Timesheet report (#140)

Co-authored-by: GigiusB <g.bronzini@gmail.com>
Co-authored-by: Jakub Rutkowski <77905816+Kubskyy@users.noreply.github.com>

* feat(Timesheet-reports): Big refactoring of timesheet reports

* feat(Timesheet-reports): Refactored and refreshed FE

* fix(admin.py): set start_date mandatory for project and provide initial value in ProjectForm (#127)

* feat(deploy.yml): Enable automatic bump upon deploy

---------

Co-authored-by: dacorsa <36949692+dacorsa@users.noreply.github.com>
Co-authored-by: Giovanni B. <g.bronzini@gmail.com>
Co-authored-by: Jakub Rutkowski <77905816+Kubskyy@users.noreply.github.com>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,25 +21,48 @@ permissions:
   packages: write
 
 jobs:
-#  bump-version:
-#    runs-on: ubuntu-latest
-#    name: "Bump version and create changelog with commitizen"
-#    permissions:
-#      contents: write
-#    outputs:
-#      version: ${{ steps.cz.outputs.version }}
-#    steps:
-#      - name: Check out
-#        uses: actions/checkout@v4
-#        with:
-#          fetch-depth: 0
-#          token: ${{ secrets.GITHUB_TOKEN }}
-#
-#      - id: cz
-#        name: Create bump and changelog
-#        uses: commitizen-tools/commitizen-action@master
-#        with:
-#          github_token: ${{ secrets.GITHUB_TOKEN }}
+  bump:
+    runs-on: ubuntu-latest
+    steps:
+      # :one: Checkout completo del repository
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # serve per tag e merge
+      # :two: Setup Python
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.x"
+      # :three: Install Commitizen
+      - name: Install Commitizen
+        run: pip install commitizen
+      # :four: Bump versione
+      - name: Bump version with Commitizen
+        id: bump
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          cz bump --yes
+          # Read the new version from __init__.py
+          new_version=$(grep -Po '__version__\s*=\s*"\K[^"]+' src/krm3/__init__.py)
+          echo "new_version=$new_version" >> $GITHUB_OUTPUT
+      # :five: Push su master + tag
+      - name: Push bump commit and tags to master
+        run: |
+          git push origin master
+          git push origin --tags
+      # :six: Sync develop con master
+      - name: Sync develop branch with master
+        run: |
+          git fetch origin develop
+          git checkout develop
+          # merge with master if any error exit the pipeline flow
+          if ! git merge origin/master --no-edit; then
+            echo ":x: Merge conflict detected! Manual intervention required."
+            exit 1
+          fi
+          git push origin develop
 
 
   build-frontend:
